### ISSUE TITLE
Re-focus after form submit

### ISSUE THREAD

**Issue by knpaing** [korniychuk/angular-autofocus-fix#7]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Using Angular Reactive Form, I am accepting continues data entry on same page where user "Submit" the data after every transaction. Once submitted, I'd like to set the focus back to the control with "autofocus" attribute. I don't know how I can achieve this. 

**Describe alternatives you've considered**
So far I am using ElementRef to re-focus. I'd be nice since this is autofocus fix.

**Additional context**
Thank you for making this feature.

**Comment by korniychuk** [comment]
What do you do on submitting the form? Do you have something like an Http request on submitting?

**Comment by knpaing** [comment]
Yes. On submitting form, I have http request and then after, I'd like to set the focus on the input again so that user doesn't need to manually move the focus again.

**Comment by korniychuk** [comment]
The problem is that in JavaScript there is no such event as `onFormSubmittingFinished`. There are too many scenarios that we can on in the `submit` event handler.

Due to this, I see only one way to solve your problem - this is manual executing `.focus()` method after your submitting logic finished.

Here is an example:

```typescript
import { ElementRef, ViewChild, Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
    <button (click)="showForm = !showForm">toggle</button>
    <div *ngIf="showForm">
      <input autofocus #myInput>
      <button (click)="onSendClick()">send</button>
    </div>
  `,
})
export class AppComponent  {
  @ViewChild('myInput', { static: false })
  public myInput?: ElementRef;

  public showForm: boolean = false;

  public onSendClick(): void {
    console.log('on click');
    setTimeout(() => {
      this.myInput && this.myInput.nativeElement.focus();
    }, 1000);
  }
}
```

[Live Example](https://stackblitz.com/edit/ngx-autofocus-fix-issue-7-example-1?file=src%2Fapp%2Fapp.component.ts)

Also, I can create a public method `focus()` on the `AutofocusFixDirective`, and after this, you will have an ability to handle focus next way:

```typescript
import { ElementRef, ViewChild, Component } from '@angular/core';
import { AutofocusFixDirective } from 'ngx-autofocus-fix';               // <--- changed

@Component({
  selector: 'my-app',
  template: `
    <button (click)="showForm = !showForm">toggle</button>
    <div *ngIf="showForm">
      <input autofocus #myInput>
      <button (click)="onSendClick()">send</button>
    </div>
  `,
})
export class AppComponent  {
  @ViewChild('myInput', { static: false, read: AutofocusFixDirective }) // <--- changed
  public myInput?: AutofocusFixDirective;                               // <--- changed

  public showForm: boolean = false;

  public onSendClick(): void {
    console.log('on click');
    setTimeout(() => {
      this.myInput && this.myInput.focus();                             // <--- changed
    }, 1000);
  }
}
```

But I'm not sure that this update will bring significant changes. I would propose you to handle it via `ElementRef`.

@knpaing May you have a proposition on how the library can handle your task? If yes - let's discuss it.
